(function(){
 'use strict';
 if(['127.0.0.1','localhost'].includes(location.hostname)&&['3000','5500'].includes(location.port)){location.replace('http://127.0.0.1:3001/admin.html');return;}
 const $=id=>document.getElementById(id);let token='',busy=false,session=0;
 const money=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 async function api(input){const r=await fetch('/api/admin-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(input),cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Não foi possível consultar os pedidos.');return data;}
 const line=(root,text,tag='p')=>{const el=document.createElement(tag);el.textContent=text;root.append(el);return el;};
 function render(orders){$('orderList').replaceChildren();for(const order of orders){const card=document.createElement('article');card.className='admin-order';line(card,'Pedido '+order.txid,'h2');line(card,'Total: '+money(order.amount));line(card,order.paidAt?'Pagamento conferido manualmente':'Aguardando conferência').className='admin-status';line(card,'Registro: '+new Date(order.createdAt.replace?.(' ','T')||order.createdAt).toLocaleString('pt-BR'));const list=document.createElement('ul');for(const item of order.items)line(list,item.title+' — '+money(item.amount),'li');card.append(list);const detail=document.createElement('details');line(detail,'Dados do cliente e entrega','summary');const c=order.customer;line(detail,c.name+' · '+c.email);line(detail,'CPF: '+c.document);line(detail,'Telefone: +'+c.phones.mobile_phone.country_code+c.phones.mobile_phone.area_code+c.phones.mobile_phone.number);line(detail,[c.address.line_1,c.address.line_2,c.address.city,c.address.state,c.address.zip_code].filter(Boolean).join(' · '));card.append(detail);if(!order.paidAt){const button=line(card,'Marcar pagamento conferido','button');button.type='button';button.addEventListener('click',()=>confirm(order,button));}$('orderList').append(card);}if(!orders.length)line($('orderList'),'Nenhum pedido registrado.');}
 async function load(){if(busy)return;busy=true;const version=session;$('adminNotice').textContent='Carregando pedidos…';try{const data=await api({action:'list'});if(version!==session)return;render(data.orders);$('adminLogin').hidden=true;$('adminActions').hidden=false;$('adminNotice').textContent=data.orders.length+' pedidos exibidos.';}catch(e){$('adminNotice').textContent=e.name==='TimeoutError'?'A consulta demorou. Tente novamente.':e.message;}finally{busy=false;}}
 async function confirm(order,button){$('confirmText').textContent='Pedido '+order.txid+' — '+money(order.amount);const dialog=$('confirmPayment');dialog.returnValue='cancel';dialog.showModal();const answer=await new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue),{once:true}));if(answer!=='confirm')return;button.disabled=true;try{await api({action:'mark_paid',id:order.id,confirmed:true});await load();}catch(e){$('adminNotice').textContent=e.message;button.disabled=false;}}
 $('adminLogin').addEventListener('submit',e=>{e.preventDefault();token=$('adminToken').value.trim();$('adminToken').value='';load();});$('refreshOrders').addEventListener('click',load);$('logout').addEventListener('click',()=>{token='';$('orderList').replaceChildren();$('adminActions').hidden=true;$('adminLogin').hidden=false;$('adminNotice').textContent='Sessão encerrada.';});
})();
